/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * TiDev Titanium Mobile
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */

package ti.tts;

import android.annotation.SuppressLint;
import android.os.Bundle;
import android.speech.tts.TextToSpeech;
import android.speech.tts.UtteranceProgressListener;
import android.speech.tts.Voice;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiBlob;
import org.appcelerator.titanium.io.TiBaseFile;
import org.appcelerator.titanium.io.TiFileFactory;

import java.util.Locale;


@Kroll.module(name = "TiTts", id = "ti.tts")
public class TiTtsModule extends KrollModule {

    private static final String LCAT = "TiTtsModule";
    private static final String defaultID = "utteranceID";
    private String lastBlobId = null;
    private TiBaseFile lastBlobFile;
    
    TextToSpeech tts;

    public TiTtsModule() {
        super();
    }

    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app) {
    }

    @SuppressLint("NewApi")
    @Kroll.method
    public String getVoices(@Kroll.argument(optional = true) String value) {
        String out = "";
        String cnc = "";
        for (Voice tmpVoice : tts.getVoices()) {
            if (value != null) {
                if (tmpVoice.getName().contains(value)) {
                    out += cnc + tmpVoice.getName();
                }
            } else {
                out += cnc + tmpVoice.getName();
            }
            cnc="|";
        }
        return out;
    }

    @Kroll.setProperty
    public void setSpeed(float value) {
        tts.setSpeechRate(value);
    }

    @Kroll.setProperty
    public void setPitch(float value) {
        tts.setPitch(value);
    }

    @SuppressLint("NewApi")
    @Kroll.setProperty
    public void setVoice(String value) {
        Voice voice = null;

        for (Voice tmpVoice : tts.getVoices()) {
            if (tmpVoice.getName().equals(value)) {
                voice = tmpVoice;
                break;
            }
        }
        if (voice != null) {
            tts.setVoice(voice);
        }
    }

    @SuppressLint("NewApi")
    @Kroll.method
    public void init() {
        tts = new TextToSpeech(TiApplication.getAppCurrentActivity(), status -> {
            KrollDict kd = new KrollDict();
            kd.put("status", status);
            emitEvents();
            fireEvent("init", kd);
        });
    }
    
    @SuppressLint("NewApi")
    @Kroll.method
    public void initSilent() {
        tts = new TextToSpeech(TiApplication.getAppCurrentActivity(), status -> {
            KrollDict kd = new KrollDict();
            kd.put("status", status);
            fireEvent("init", kd);
        });
    }

    @SuppressLint("NewApi")
    @Kroll.method
       
    public void speak(KrollDict params) {
        String value = params.getString("text");
        String uid = params.optString("uid", TiTtsModule.defaultID);
        int mode = params.optBoolean("flush",false) ? TextToSpeech.QUEUE_FLUSH : TextToSpeech.QUEUE_ADD;
        Bundle bundle = null;
        if (params.containsKey("volume")||params.containsKey("pan") ) {
         bundle=new Bundle();
         if (params.containsKey("volume"))
          bundle.putFloat(TextToSpeech.Engine.KEY_PARAM_VOLUME, params.getDouble("volume").floatValue()); // [ from 0.0 to 1.0 ]
         if (params.containsKey("pan"))
          bundle.putFloat(TextToSpeech.Engine.KEY_PARAM_PAN, params.getDouble("pan").floatValue()); // [ from -1.0 to 1.0 ]
        }
        tts.speak(value, mode, bundle, uid);
    }

    @SuppressLint("NewApi")
    @Kroll.setProperty
    public void setLanguage(String value) {
        tts.setLanguage(Locale.forLanguageTag(value));
    }
    
    @SuppressLint("NewApi")
    @Kroll.getProperty
    public int getBufferlen() {
        return TextToSpeech.getMaxSpeechInputLength();
    }
    
    @SuppressLint("NewApi")
    @Kroll.getProperty
    public boolean getSpeaking() {
        return tts.isSpeaking();
    }

    @SuppressLint("NewApi")
    @Kroll.method
    public String synthesizeToFile(KrollDict params) {
        String value = params.getString("text");
        String uid = params.optString("uid", TiTtsModule.defaultID);
        String fileName = params.optString("filename", System.currentTimeMillis() + ".wav");
        Bundle bundle = new Bundle();
        bundle.putString(TextToSpeech.Engine.KEY_PARAM_UTTERANCE_ID, uid);
        if ( params.containsKey("volume") || params.containsKey("pan") ) {
         bundle=new Bundle();
         if (params.containsKey("volume"))
          bundle.putFloat(TextToSpeech.Engine.KEY_PARAM_VOLUME, params.getDouble("volume").floatValue()); // [ from 0.0 to 1.0 ]
         if (params.containsKey("pan"))
          bundle.putFloat(TextToSpeech.Engine.KEY_PARAM_PAN, params.getDouble("pan").floatValue()); // [ from -1.0 to 1.0 ]
        }
        try {
            TiBaseFile outfile = TiFileFactory.createTitaniumFile(fileName, true);
            tts.synthesizeToFile(value, bundle, outfile.getNativeFile(), uid);
            if (params.optBoolean("blob",true)) {
             lastBlobId = uid;
             lastBlobFile = outfile;
            }
            return outfile.nativePath();
        } catch (Exception e) {
            return null;
        }
    }

    @SuppressLint("NewApi")
    @Kroll.method
    public int emitEvents() {
        return tts.setOnUtteranceProgressListener(new UtteranceProgressListener() {
                @Override
                public void onStart(String utteranceId) {
                    KrollDict kd = new KrollDict();
                    kd.put("id", utteranceId);
                    fireEvent("start", kd);
                }

                @Override
                public void onDone(String utteranceId) {
                    KrollDict kd = new KrollDict();
                    kd.put("id", utteranceId);
                    if (utteranceId.equals(lastBlobId))
                     kd.put("blob", TiBlob.blobFromFile(lastBlobFile));
                    lastBlobFile=null;
                    lastBlobId=null;
                    fireEvent("done", kd);
                }

                @Override
                public void onError(String utteranceId, int code) {
                    KrollDict kd = new KrollDict();
                    kd.put("id", utteranceId);
                    kd.put("code", code);
                    fireEvent("error", kd);
                }

                @Override
                @Deprecated
                public void onError(String utteranceId) {
                    KrollDict kd = new KrollDict();
                    kd.put("id", utteranceId);
                    fireEvent("error", kd);
                }

                @Override
                public void onStop(String utteranceId, boolean interrupted) {
                    KrollDict kd = new KrollDict();
                    kd.put("id", utteranceId);
                    kd.put("interrupted", interrupted);
                    fireEvent("stop", kd);
                }
            });
    }
    
    @SuppressLint("NewApi")
    @Kroll.method
    public void shutdown() {
        tts.shutdown();
    }

    @SuppressLint("NewApi")
    @Kroll.method
    public int stop() {
        return tts.stop();
    }

}
